In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

In [2]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [99, 56, 43],
                   [80, 44, 17],
                   [111, 58, 84],
                   [48, 34, 58],
                   [41, 78, 94],
                   [107, 54, 37],
                   [91, 88, 64],
                   [103, 135, 90],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [3]:
targets = np.array([[58, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [82, 100],
                    [20, 38],
                    [104, 118],
                    [102, 120]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [7]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 99.,  56.,  43.],
        [ 80.,  44.,  17.],
        [111.,  58.,  84.],
        [ 48.,  34.,  58.],
        [ 41.,  78.,  94.],
        [107.,  54.,  37.],
        [ 91.,  88.,  64.],
        [103., 135.,  90.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [8]:
from torch.utils.data import TensorDataset

In [9]:
ds = TensorDataset(inputs,targets)

In [11]:
ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 58.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [12]:
from torch.utils.data import DataLoader

In [13]:
batch_size = 5
train1 = DataLoader(ds,batch_size,shuffle=True)

In [15]:
for xb,yb in train1:
    print(xb)
    print(yb)
    break

tensor([[103., 135.,  90.],
        [ 73.,  67.,  43.],
        [ 48.,  34.,  58.],
        [ 41.,  78.,  94.],
        [ 87., 134.,  58.]])
tensor([[ 20.,  38.],
        [ 58.,  70.],
        [ 80., 102.],
        [118., 132.],
        [119., 133.]])


In [16]:
model = nn.Linear(3,2)

In [17]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4870, -0.3416,  0.3850],
        [ 0.3560, -0.4238,  0.2461]], requires_grad=True)
Parameter containing:
tensor([-0.2751, -0.3626], requires_grad=True)


In [18]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4870, -0.3416,  0.3850],
         [ 0.3560, -0.4238,  0.2461]], requires_grad=True),
 Parameter containing:
 tensor([-0.2751, -0.3626], requires_grad=True)]

In [19]:
pred = model(inputs)

In [20]:
pred

tensor([[-42.1601,   7.8119],
        [-50.0150,  10.4878],
        [-66.0903, -11.9060],
        [-51.0656,  21.7287],
        [-47.7232,  13.6525],
        [-41.8076,  35.2420],
        [-12.9362,  16.5883],
        [-10.6965,   4.3093],
        [-56.5889,  23.9475],
        [-50.0150,  10.4878],
        [-61.9040,   1.2402],
        [-50.3961,  26.8292],
        [-39.7228,   0.7427]], grad_fn=<AddmmBackward0>)

In [21]:
import torch.nn.functional as F

In [22]:
loss_fn = F.mse_loss

In [23]:
loss = loss_fn(model(inputs) , targets)

In [24]:
print(loss)

tensor(11529.9326, grad_fn=<MseLossBackward0>)


In [25]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [27]:
def fit(num_epochs, model, loss_fn, opt,ds):
    for epoch in range(num_epochs):
        for xb,yb in train1:
            pred = model(xb)
            loss = loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if(epoch+1) % 10 ==0:
            print('Epoch [{}/{}], Loss: {:-4f}'.format(epoch+1 , num_epochs, loss.item()))

In [31]:
fit(100,model,loss_fn,opt,ds)

Epoch [10/100], Loss: 4447.639160
Epoch [20/100], Loss: 739.143005
Epoch [30/100], Loss: 796.794617
Epoch [40/100], Loss: 1244.005371
Epoch [50/100], Loss: 1013.522949
Epoch [60/100], Loss: 1044.442749
Epoch [70/100], Loss: 3421.114014
Epoch [80/100], Loss: 4281.611328
Epoch [90/100], Loss: 575.284851
Epoch [100/100], Loss: 1948.941772


In [32]:
pred = model(inputs)
pred

tensor([[ 58.1702,  70.9900],
        [ 79.6470,  96.5298],
        [ 87.6166, 104.2774],
        [ 61.0209,  76.7032],
        [ 38.8905,  50.1424],
        [ 87.4172, 107.7284],
        [ 52.3074,  62.8697],
        [ 82.8386,  96.0740],
        [ 58.8723,  74.9889],
        [ 79.6470,  96.5298],
        [109.5442, 130.5831],
        [ 54.8305,  70.1933],
        [ 80.2810,  95.1895]], grad_fn=<AddmmBackward0>)

In [33]:
targets

tensor([[ 58.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [ 82., 100.],
        [ 20.,  38.],
        [104., 118.],
        [102., 120.]])