In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
df = pd.read_csv(r"C:\Users\PC\OneDrive\Desktop\Dataset.csv")

In [3]:
df

Region  Temp  Rainfall  Humidity  Apples  Oranges
0   Kanto    73        67        43      58       70
1   Johto    91        88        64      81      101
2   Hoenn    87       134        58     119      133
3  Sinnoh   102        43        37      22       37
4   Unova    69        96        70     103      119

In [4]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

targets = np.array([[58, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [5]:
inputs_tensor = torch.from_numpy(inputs)
targets_tensor = torch.from_numpy(targets)

In [6]:
print("Inputs Tensor:")
print(inputs_tensor)

print("\nTargets Tensor:")
print(targets_tensor)

Inputs Tensor:
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

Targets Tensor:
tensor([[ 58.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
w = torch.randn(2,3,requires_grad= True)
b = torch.randn(2,requires_grad= True)

print(w)
print(b)

tensor([[-0.0221, -4.2427, -0.0795],
        [-1.7813,  0.7060, -1.3998]], requires_grad=True)
tensor([-1.8038, -0.9566], requires_grad=True)


In [10]:
inputs_tensor

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [12]:
inputs_tensor @ w.t() + b

tensor([[-291.0970, -143.8834],
        [-382.2611, -190.5172],
        [-576.8578, -142.5165],
        [-189.4380, -204.0880],
        [-416.1924, -154.0782]], grad_fn=<AddBackward0>)

In [13]:
def model(x):
    return x @ w.t() + b

In [15]:
pred = model(inputs_tensor)
print(pred)

tensor([[-291.0970, -143.8834],
        [-382.2611, -190.5172],
        [-576.8578, -142.5165],
        [-189.4380, -204.0880],
        [-416.1924, -154.0782]], grad_fn=<AddBackward0>)


In [16]:
print(targets_tensor)

tensor([[ 58.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [22]:
def mse(t1,t2):
    diff = t1 - t2
    return torch.sum(diff*diff) / diff.numel()

In [23]:
loss = mse(pred,targets_tensor)
print(loss)

tensor(147429.7344, grad_fn=<DivBackward0>)


In [24]:
loss.backward()

In [27]:
print(w)
print(w - w.grad * 1e-5)

tensor([[-0.0221, -4.2427, -0.0795],
        [-1.7813,  0.7060, -1.3998]], requires_grad=True)
tensor([[ 0.3490, -3.8100,  0.1789],
        [-1.5623,  0.9330, -1.2561]], grad_fn=<SubBackward0>)


In [26]:
print(b)
print(b.grad)

tensor([-1.8038, -0.9566], requires_grad=True)
tensor([-447.7693, -259.0167])


In [28]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [29]:
print(w)
print(b)

tensor([[ 0.3490, -3.8100,  0.1789],
        [-1.5623,  0.9330, -1.2561]], requires_grad=True)
tensor([-1.7993, -0.9540], requires_grad=True)


In [30]:
pred = model(inputs_tensor)
loss = mse(pred,targets_tensor)
print(loss)

tensor(100817.6641, grad_fn=<DivBackward0>)


In [31]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [33]:
pred = model(inputs_tensor)
print(pred)

tensor([[-223.9001, -106.4995],
        [-293.8717, -141.4047],
        [-471.6003,  -84.7021],
        [-123.4123, -166.6601],
        [-330.9566, -107.1075]], grad_fn=<AddBackward0>)


In [34]:
loss = mse(pred,targets_tensor)
print(loss)

tensor(100817.6641, grad_fn=<DivBackward0>)


In [35]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-30169.8652, -35785.8047, -21225.1055],
        [-18051.6250, -18558.5762, -11818.6113]])
tensor([-365.3482, -213.2748])


In [36]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [37]:
print(w)
print(b)

tensor([[ 0.6507, -3.4521,  0.3911],
        [-1.3817,  1.1186, -1.1379]], requires_grad=True)
tensor([-1.7956, -0.9519], requires_grad=True)


In [38]:
pred = model(inputs_tensor)
loss = mse(pred,targets_tensor)
print(loss)

tensor(69388.6094, grad_fn=<DivBackward0>)


In [53]:
for i in range(100):
    pred = model(inputs_tensor)
    loss = mse(pred,targets_tensor)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [54]:
pred = model(inputs_tensor)
loss = mse(pred,targets_tensor)
print(loss)

tensor(86.1285, grad_fn=<DivBackward0>)


In [55]:
pred

tensor([[ 57.8955,  70.7449],
        [ 88.1984,  92.9951],
        [105.4804, 149.7103],
        [ 26.3644,  39.6551],
        [108.7906, 104.0608]], grad_fn=<AddBackward0>)

In [56]:
targets

array([[ 58.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)